# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vooshi | Tracey Talevich | Front-End Web Developer | Seattle, WA 
email: tracey@vooshi.com
description: > # this means to ignore newlines until "baseurl:"
    Web Design / Front-End Development / SEO / UI and UX design	by Tracey Talevich in Seattle, WA
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vooshi.com" # the base hostname & protocol for your site, change to Vooshi
twitter_username: Vooshi_
github_username:  ttalevich
linkedin_username: tracey-talevich
# Build settings
markdown: kramdown
exclude:
  - package.json
  - node_modules
  - gulpfile.js
gems:
  - jekyll
  - jekyll-seo-tag
  - jekyll-sitemap
