# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://127.0.0.1:4000 # the base hostname & protocol for your site, chagne to Vooshi
twitter_username: Vooshi_
github_username:  ttalevich
linkedin_username: tracey-talevich
# Build settings
markdown: kramdown
exclude:
  - package.json
  - node_modules
  - gulpfile.js
